version: 2.0.{build}-alpha
branches:
  only:
  - trunk
image: Visual Studio 2022
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  project: Cinegy.KlvDecoder.sln
  publish_nuget: true
  verbosity: minimal
before_build:
- cmd: nuget restore
after_build:
- cmd: >-
    7z a Cinegy.KlvDecoder-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%-PDB.zip %APPVEYOR_BUILD_FOLDER%\Cinegy.KlvDecoder\bin

    appveyor PushArtifact Cinegy.KlvDecoder-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%-PDB.zip
# deploy:
# - provider: NuGet
#   api_key:
#     secure: qeOuGvsrtZ2CDCuuOUr3b4h2F9n7clZtYypnvi7xA/EvSMF/w4/FKRtcff2mUb4m
#   skip_symbols: true